import { NextRequest, NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { previews } from "@/lib/db/schema";
import {
  getPreviewGenerationQueue,
  type PreviewGenerationJobData,
} from "@/lib/queue/queues";
import { getSessionUser } from "@/lib/services/customer-auth";
import { rateLimitAsync } from "@/lib/services/rate-limit";
import { getClientIpFromRequest } from "@/lib/utils/request";
import { reserveSpend, releaseSpend } from "@/lib/services/spend-guard";
import { isFlagEnabled } from "@/lib/services/flags";

// Bound regenerate cost: each round is N image-to-image calls. Customer gets the
// initial round + up to 3 retries.
const MAX_VARIATION_ROUNDS = 4;

// One round = VARIATION_COUNT (2) fal calls at ~4 US cents each.
const ROUND_COST_CENTS = 8;

// Customer disliked both variations → re-run Stage A with a fresh round.
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;

  // This route used to be fully unauthenticated, un-rate-limited and
  // un-metered while spending real fal.ai budget on every call — anyone
  // holding a preview UUID could burn the budget four rounds at a time.
  const session = await getSessionUser();

  const preview = await db.query.previews.findFirst({
    where: eq(previews.id, id),
  });
  if (!preview) {
    return NextResponse.json({ error: "not found" }, { status: 404 });
  }

  // A preview with an owner may only be regenerated by that owner. Anonymous
  // previews (userId null) stay reachable by whoever holds the UUID, which is
  // how the pre-login create flow works.
  if (preview.userId && preview.userId !== session?.userId) {
    return NextResponse.json(
      { error: "not found" },
      { status: 404 },
    );
  }

  if (preview.status !== "styled") {
    return NextResponse.json({ error: "not regenerable" }, { status: 409 });
  }
  if ((preview.variationRounds ?? 1) >= MAX_VARIATION_ROUNDS) {
    return NextResponse.json(
      { error: "limit reached", code: "regenerate_cap" },
      { status: 429 },
    );
  }

  const ip = getClientIpFromRequest(request);
  const perPreview = await rateLimitAsync(`regen:preview:${id}`, 4, 60 * 60 * 1000);
  const perIp = await rateLimitAsync(`regen:ip:${ip}`, 20, 60 * 60 * 1000);
  if (!perPreview.success || !perIp.success) {
    return NextResponse.json(
      { error: "too many requests", code: "rate_limited" },
      { status: 429 },
    );
  }

  if (!(await isFlagEnabled("fal_enabled"))) {
    return NextResponse.json(
      { error: "generation is temporarily unavailable", code: "disabled" },
      { status: 503 },
    );
  }

  const reservation = await reserveSpend("fal", ROUND_COST_CENTS, {
    kind: "order",
    id,
  });
  if (!reservation.ok) {
    return NextResponse.json(
      { error: "budget exhausted", code: reservation.reason },
      { status: 429 },
    );
  }

  try {
    await db
      .update(previews)
      .set({
        status: "generating",
        styledImageUrls: null,
        variationRounds: (preview.variationRounds ?? 1) + 1,
        updatedAt: new Date(),
      })
      .where(eq(previews.id, id));

    await getPreviewGenerationQueue().add("generate-variations", {
      previewId: id,
      imageUrl: preview.photoUrl,
      photoKey: preview.photoKey,
      photoKeys: preview.photoKeys ?? undefined,
      style: preview.style,
      modifiers: preview.modifiers ?? [],
    } satisfies PreviewGenerationJobData);
  } catch (err) {
    await releaseSpend(reservation.reservationId);
    throw err;
  }

  return NextResponse.json({ status: "generating" });
}
