import { NextRequest, NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { previews } from "@/lib/db/schema";
import {
  getPreviewGenerationQueue,
  type PreviewGenerationJobData,
} from "@/lib/queue/queues";
import { getSessionUser } from "@/lib/services/customer-auth";
import { rateLimitAsync } from "@/lib/services/rate-limit";
import { getClientIpFromRequest } from "@/lib/utils/request";
import { reserveSpend, releaseSpend } from "@/lib/services/spend-guard";
import { isFlagEnabled } from "@/lib/services/flags";
import { handleRouteFailure, CUSTOMER_ACTION_FAILED_ERROR } from "@/lib/api/route-error";

// Bound regenerate cost: each round is N image-to-image calls. Customer gets the
// initial round + up to 3 retries.
const MAX_VARIATION_ROUNDS = 4;

// One round = VARIATION_COUNT (2) fal calls at ~4 US cents each.
const ROUND_COST_CENTS = 8;

// Customer disliked both variations → re-run Stage A with a fresh round.
async function handlePOST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;

  // This route used to be fully unauthenticated, un-rate-limited and
  // un-metered while spending real fal.ai budget on every call — anyone
  // holding a preview UUID could burn the budget four rounds at a time.
  const session = await getSessionUser();

  const preview = await db.query.previews.findFirst({
    where: eq(previews.id, id),
  });
  if (!preview) {
    return NextResponse.json({ error: "not found" }, { status: 404 });
  }

  // A preview with an owner may only be regenerated by that owner. Anonymous
  // previews (userId null) stay reachable by whoever holds the UUID, which is
  // how the pre-login create flow works.
  if (preview.userId && preview.userId !== session?.userId) {
    return NextResponse.json(
      { error: "not found" },
      { status: 404 },
    );
  }

  if (preview.status !== "styled") {
    return NextResponse.json({ error: "not regenerable" }, { status: 409 });
  }
  if ((preview.variationRounds ?? 1) >= MAX_VARIATION_ROUNDS) {
    return NextResponse.json(
      { error: "limit reached", code: "regenerate_cap" },
      { status: 429 },
    );
  }

  const ip = getClientIpFromRequest(request);
  const perPreview = await rateLimitAsync(`regen:preview:${id}`, 4, 60 * 60 * 1000);
  const perIp = await rateLimitAsync(`regen:ip:${ip}`, 20, 60 * 60 * 1000);
  if (!perPreview.success || !perIp.success) {
    return NextResponse.json(
      {
        error:
          "Çok fazla deneme yaptınız. Bir süre bekleyip tekrar deneyin.",
        code: "rate_limited",
      },
      { status: 429 },
    );
  }

  if (!(await isFlagEnabled("fal_enabled"))) {
    return NextResponse.json(
      {
        error:
          "Görsel üretimi şu anda geçici olarak kapalı. Kısa süre sonra tekrar deneyin.",
        code: "disabled",
      },
      { status: 503 },
    );
  }

  const reservation = await reserveSpend("fal", ROUND_COST_CENTS, {
    kind: "order",
    id,
  });
  if (!reservation.ok) {
    return NextResponse.json(
      {
        error:
          "Görsel üretimi şu anda yoğun. Kısa süre sonra tekrar deneyin.",
        code: reservation.reason,
      },
      { status: 429 },
    );
  }

  // Nereye kadar gelindi: TUR AÇILDI MI? Beklenmeyen bir hatada müşteriye ne
  // diyeceğimizi bu ayrım belirler — sayaç arttıysa "hiçbir şey değişmedi"
  // demek yalan olur (müşterinin 4 turluk hakkından biri gitmiştir).
  let roundOpened = false;
  try {
    await db
      .update(previews)
      .set({
        status: "generating",
        styledImageUrls: null,
        variationRounds: (preview.variationRounds ?? 1) + 1,
        updatedAt: new Date(),
      })
      .where(eq(previews.id, id));
    roundOpened = true;

    await getPreviewGenerationQueue().add("generate-variations", {
      previewId: id,
      imageUrl: preview.photoUrl,
      photoKey: preview.photoKey,
      photoKeys: preview.photoKeys ?? undefined,
      style: preview.style,
      modifiers: preview.modifiers ?? [],
    } satisfies PreviewGenerationJobData);
  } catch (err) {
    console.error("preview yeniden üretim: tur başlatılamadı", err);
    // Rezervasyon telafisi: tur başlamadığına göre ayrılan bütçe geri verilir.
    // Kendi hatasını yutar — telafinin patlaması, müşteriye söylenecek cümleyi
    // yine boş bırakırdı.
    await releaseSpend(reservation.reservationId).catch((e) =>
      console.error("preview yeniden üretim: rezervasyon geri verilemedi", e)
    );
    // Burada eskiden `throw err` vardı: Next onu SIFIR BAYTLIK bir 500'e
    // çeviriyor, /create ekranı da kendi yedek cümlesini gösteriyordu. Müşteri
    // ne olduğunu, turunun yanıp yanmadığını ve ne yapacağını okuyamıyordu.
    return NextResponse.json(
      {
        error: roundOpened
          ? "Yeni tur açıldı ancak görsel üretimi sıraya alınamadı. Bu tur birkaç dakika içinde başarısız olarak işaretlenecek; sonrasında yeniden deneyebilirsiniz."
          : "Beklenmeyen bir hata nedeniyle yeni tur başlatılamadı; görselleriniz ve deneme hakkınız olduğu gibi duruyor, tekrar deneyebilirsiniz.",
        reason: "unexpected_error",
      },
      { status: 500 }
    );
  }

  return NextResponse.json({ status: "generating" });
}

/**
 * Beklenmeyen hata = GÖVDESİ OLAN cevap. Ön okumalar (oturum, önizleme, hız
 * sınırı, bütçe rezervasyonu) da bu yakalamanın içinde kalsın diye işin tamamı
 * `handlePOST` üzerinden geçer — biri patlarsa müşteriye yine Türkçe bir cümle
 * gider (gerekçe: src/lib/api/route-error.ts).
 */
export async function POST(
  request: NextRequest,
  ctx: { params: Promise<{ id: string }> },
) {
  try {
    return await handlePOST(request, ctx);
  } catch (e) {
    return handleRouteFailure(
      e,
      "POST /api/preview/[id]/regenerate",
      CUSTOMER_ACTION_FAILED_ERROR
    );
  }
}
